getToken:
    path: /user
    methods: GET
    controller: App\Controller\UserController::index

index:
    path: /{reactRouting}
    controller: App\Controller\HomeController::index
    defaults:
        reactRouting: null
